openapi: 3.0.1
info:
  title: Documentación de la App Tienda
  description: E-commerce
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/products:
    get:
      summary: Obtenemos todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Todos los productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor
    post:
      summary: Crea un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/CreateProduct"
      responses:
        "200":
          description: Producto agregado correctamente
        "500":
          description: Stock o Price es un string y deben ser number

  /api/products/{pid}:
    get:
      summary: Obtiene un solo producto por ID
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: ID del producto que se quiere buscar
        schema:
          type: string
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor
    put:
      summary: Actualiza un producto por ID
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: ID del producto que se quiere actualizar
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/UpdateProduct"
      responses:
        "200":
          description: Producto actualizado correctamente
        "500":
          description: Error interno del servidor
    delete:
      summary: Elimina un producto por ID
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: ID del producto que se quiere eliminar
        schema:
          type: string
      responses:
        "200":
          description: Producto eliminado correctamente
        "500":
          description: Error interno del servidor

  /api/products/test/mockingproducts:
    get:
      summary: Genera productos de prueba con Faker
      tags:
        - Products
      responses:
        "200":
          description: Productos de prueba generados correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: Id autogenerado por MongoDB
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
        code:
          type: string
          description: Código único del producto
        stock:
          type: number
          description: Cantidad en stock del producto
        status:
          type: boolean
          description: Estado del producto (true/false)
        category:
          type: string
          description: Categoría del producto
        owner:
          type: string
          description: Propietario del producto
      example:
        _id: "60c72b2f9b1d8b3a8f6f8b4d"
        title: "Producto de ejemplo I"
        description: "Descripción del producto de ejemplo I"
        price: 100
        thumbnail: "http://example.com/imagen-ejemplo.png"
        code: "abc999"
        stock: 25
        status: true
        category: "string"
        owner: "Admin"
  requestBodies:
    CreateProduct:
      type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
        code:
          type: string
          description: Código único del producto
        stock:
          type: number
          description: Cantidad en stock del producto
        status:
          type: boolean
          description: Estado del producto (true/false)
        category:
          type: string
          description: Categoría del producto
        owner:
          type: string
          description: Propietario del producto
      example:
        title: "Producto de ejemplo II"
        description: "Descripción del producto de ejemplo II"
        price: 100
        thumbnail: "http://example.com/imagen-ejemplo-II.png"
        code: "abc000"
        stock: 25
        status: true
        category: "string"
        owner: "abc@example.com"
    UpdateProduct:
      type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
        code:
          type: string
          description: Código único del producto
        stock:
          type: number
          description: Cantidad en stock del producto
        status:
          type: boolean
          description: Estado del producto
        category:
          type: string
          description: Categoría del producto
        owner:
          type: string
          description: Propietario del producto
      example:
        title: "Producto de ejemplo updated"
        description: "Descripción actualizada del producto"
        price: 999
        thumbnail: "http://example.com/imagen-updated.png"
        code: "abc9999"
        stock: 15
        status: true
        category: "Categoría updated"
        owner: "Admin"